### ISSUE TITLE
Lỗi kết nối home assistant

### ISSUE THREAD

**Issue by tiboy8x** [olli-ai/maika_assistant#11]
Vẫn bị lỗi 400: Bad request

```
maika_assistant:
  project_id: "MAIKA"
  url: http://homeassistant.local:8123
  api_key: .....
  report_state: true

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.1.0/24
    - 127.0.0.1
    - ::1

```
